### ISSUE TITLE
Адаптив

### ISSUE THREAD

**Issue by GrigorenkoSergey** [KsuVla/2task#18]
Проверь все страницы на диапазон 320-1920px в FF (хром глючит). Горизонтальных полос прокрутки появляться не должно.

**Comment by KsuVla** [comment]
В FF проверила, не заметила нигде прокрутки (ui-kit не в счет), может все исправилось при чистке стилей.

Но в ui-kit срабатывали media, которые мне не нужны (статичные же страницы фиксированной ширины), разделила стили блоков, где необходимо, на две части (основной и медиа)

**Comment by GrigorenkoSergey** [comment]
Еще не смотрел по всем страницам, но не стоило делить на разные части. Это запутывает.
